using UnityEngine;

public static class Streets
{
    public static string Random { get { return All[UnityEngine.Random.Range(0, All.Length)]; } }

    public static readonly string[] All = new[]
    {
        "Pennsylvania Avenue",
        "Overlook Circle",
        "Pearl Street",
        "Hickory Lane",
        "Oak Lane",
        "Oxford Court",
        "Aspen Drive",
        "Clinton Street",
        "5th Street East",
        "Glenwood Drive",
        "Walnut Street",
        "Washington Street",
        "Harrison Street",
        "Linda Lane",
        "Sheffield Drive",
        "4th Street North",
        "Laurel Street",
        "Cedar Lane",
        "6th Street",
        "Myrtle Avenue",
        "Willow Lane",
        "Laurel Drive",
        "Dogwood Lane",
        "5th Street",
        "Jackson Street",
        "Pheasant Run",
        "Riverside Drive",
        "Canterbury Drive",
        "Oxford Road",
        "Jefferson Court",
        "3rd Street North",
        "Main Street West",
        "Highland Drive",
        "Roberts Road",
        "Tanglewood Drive",
        "Brookside Drive",
        "Morris Street",
        "Pleasant Street",
        "Colonial Drive",
        "Park Street",
        "Summer Street",
        "Warren Avenue",
        "Cemetery Road",
        "Beech Street",
        "High Street",
        "Arch Street",
        "Virginia Street",
        "Chapel Street",
        "4th Street",
        "Chestnut Street",
        "Bank Street",
        "Summit Avenue",
        "Country Lane",
        "Hillside Drive",
        "Route 17",
        "B Street",
        "Homestead Drive",
        "Mill Road",
        "2nd Street North",
        "Fairview Road",
        "Ridge Road",
        "Jefferson Avenue",
        "Eagle Street",
        "Grant Street",
        "Fieldstone Drive",
        "Devon Road",
        "Madison Avenue",
        "Lantern Lane",
        "Route 11",
        "3rd Street West",
        "Euclid Avenue",
        "Main Street South",
        "4th Street South",
        "Pine Street",
        "Hawthorne Avenue",
        "4th Avenue",
        "Wood Street",
        "Sycamore Lane",
        "Railroad Street",
        "Henry Street",
        "Grant Avenue",
        "Bayberry Drive",
        "Hamilton Road",
        "Route 7",
        "Broad Street",
        "River Street",
        "George Street",
        "Lake Street",
        "Madison Court",
        "North Avenue",
        "7th Street",
        "Circle Drive",
        "Adams Avenue",
        "9th Street West",
        "Charles Street",
        "Front Street North",
        "Cooper Street",
        "Depot Street",
        "York Street",
        "Elmwood Avenue",
        "Route 20",
        "Cherry Lane",
        "Atlantic Avenue",
        "Delaware Avenue",
        "Laurel Lane",
        "8th Street South",
        "School Street",
        "Route 41",
        "Orchard Street",
        "Spring Street",
        "Deerfield Drive",
        "Church Street North",
        "West Street",
        "Jefferson Street",
        "5th Street South",
        "Warren Street",
        "Route 1",
        "Grove Street",
        "Church Street",
        "Cambridge Road",
        "College Avenue",
        "Green Street",
        "Willow Street",
        "Ann Street",
        "Water Street",
        "Manor Drive",
        "Virginia Avenue",
        "Briarwood Court",
        "Lake Avenue",
        "Fawn Court",
        "Fairview Avenue",
        "Cedar Street",
        "Route 29",
        "Route 9",
        "Liberty Street",
        "Walnut Avenue",
        "Clay Street",
        "Surrey Lane",
        "Route 44",
        "2nd Street East",
        "Crescent Street",
        "Somerset Drive",
        "Ridge Street",
        "Queen Street",
        "Mulberry Street",
        "Brown Street",
        "Ridge Avenue",
        "Holly Drive",
        "Washington Avenue",
        "6th Street North",
        "Route 27",
        "Valley View Road",
        "Roosevelt Avenue",
        "Locust Street",
        "Mulberry Court",
        "Front Street South",
        "Holly Court",
        "Hudson Street",
        "14th Street",
        "New Street",
        "Edgewood Drive",
        "Woodland Avenue",
        "Heather Court",
        "Jones Street",
        "Bay Street",
        "Hamilton Street",
        "Lawrence Street",
        "Howard Street",
        "Victoria Court",
        "Forest Street",
        "Hillcrest Avenue",
        "Center Street",
        "Durham Road",
        "Willow Drive",
        "Orchard Lane",
        "Country Club Drive",
        "Park Place",
        "Taylor Street",
        "York Road",
        "Parker Street",
        "Church Street South",
        "Catherine Street",
        "Meadow Street",
        "Belmont Avenue",
        "Ivy Court",
        "River Road",
        "Cross Street",
        "Old York Road",
        "Hawthorne Lane",
        "College Street",
        "Rosewood Drive",
        "Windsor Drive",
        "Maple Avenue",
        "Woodland Drive",
        "8th Street West",
        "Canal Street",
        "Woodland Road",
        "Fulton Street",
        "Oak Street",
        "Valley View Drive",
        "Harrison Avenue",
        "Division Street",
        "Broad Street West",
        "Linden Avenue",
        "Penn Street",
        "12th Street East",
        "2nd Street West",
        "Elm Avenue",
        "12th Street",
        "Augusta Drive",
        "Glenwood Avenue",
        "East Avenue",
        "Marshall Street",
        "Prospect Avenue",
        "Adams Street",
        "Lakeview Drive",
        "Elizabeth Street",
        "Hartford Road",
        "Rose Street",
        "Hill Street",
        "Brandywine Drive",
        "Route 6",
        "7th Avenue",
        "Cleveland Street",
        "1st Avenue",
        "Meadow Lane",
        "Main Street East",
        "Route 64",
        "Route 4",
        "Main Street North",
        "Linden Street",
        "Cambridge Court",
        "Union Street",
        "Street Road",
        "Elm Street",
        "Lafayette Avenue",
        "Cardinal Drive",
        "King Street",
        "Route 100",
        "Lexington Drive",
        "Forest Drive",
        "Essex Court",
        "Eagle Road",
        "Locust Lane",
        "Maple Lane",
        "13th Street",
        "Highland Avenue",
        "Grand Avenue",
        "Evergreen Lane",
        "Poplar Street",
        "2nd Street",
        "Country Club Road",
        "Mechanic Street",
        "Valley Road",
        "Route 202",
        "Shady Lane",
        "Beechwood Drive",
        "Heritage Drive",
        "11th Street",
        "Clark Street",
        "Evergreen Drive",
        "State Street",
        "Broadway",
        "Orange Street",
        "Ashley Court",
        "Ivy Lane",
        "John Street",
        "6th Avenue",
        "Primrose Lane",
        "Bridle Lane",
        "5th Street North",
        "6th Street West",
        "3rd Avenue",
        "Route 32",
        "Academy Street",
        "Lafayette Street",
        "Myrtle Street",
        "Forest Avenue",
        "Canterbury Road",
        "Brook Lane",
        "Lexington Court",
        "Carriage Drive",
        "5th Street West",
        "Buttonwood Drive",
        "Dogwood Drive",
        "Arlington Avenue",
        "Columbia Street",
        "Fawn Lane",
        "Franklin Street",
        "Jackson Avenue",
        "Hillcrest Drive",
        "Strawberry Lane",
        "Central Avenue",
        "Front Street",
        "Briarwood Drive",
        "Lilac Lane",
        "Magnolia Court",
        "4th Street West",
        "Colonial Avenue",
        "Pin Oak Drive",
        "Bridge Street",
        "Mill Street",
        "Magnolia Drive",
        "Chestnut Avenue",
        "Devon Court",
        "3rd Street",
        "Creekside Drive",
        "Devonshire Drive",
        "Sherwood Drive",
        "Mulberry Lane",
        "Orchard Avenue",
        "Cleveland Avenue",
        "Sunset Drive",
        "William Street",
        "Franklin Avenue",
        "Buckingham Drive",
        "Park Avenue",
        "Williams Street",
        "Lincoln Street",
        "Railroad Avenue",
        "Winding Way",
        "Maiden Lane",
        "Cambridge Drive",
        "Berkshire Drive",
        "Race Street",
        "1st Street",
        "North Street",
        "Durham Court",
        "State Street East",
        "Spruce Street",
        "Creek Road",
        "Park Drive",
        "James Street",
        "East Street",
        "Prospect Street",
        "Hillside Avenue",
        "9th Street",
        "Fairway Drive",
        "Garfield Avenue",
        "Monroe Drive",
        "Garden Street",
        "Windsor Court",
        "Route 5",
        "Vine Street",
        "Grove Avenue",
        "South Street",
        "Sycamore Drive",
        "Route 70",
        "Oak Avenue",
        "8th Avenue",
        "Hilltop Road",
        "Redwood Drive",
        "Heather Lane",
        "Bridle Court",
        "Inverness Drive",
        "Willow Avenue",
        "Schoolhouse Lane",
        "Smith Street",
        "3rd Street East",
        "Cedar Court",
        "Westminster Drive",
        "Wall Street",
        "Route 30",
        "Franklin Court",
        "Lincoln Avenue",
        "Edgewood Road",
        "Main Street",
        "Market Street",
        "Cedar Avenue",
        "Maple Street",
        "Sycamore Street",
        "Sunset Avenue",
        "Spruce Avenue",
        "2nd Avenue",
        "5th Avenue",
        "Valley Drive",
        "Sherman Street",
        "10th Street",
        "Madison Street",
        "Magnolia Avenue",
        "Cherry Street",
        "Cottage Street",
        "Cypress Court",
        "Aspen Court",
        "8th Street",
        "Hickory Street",
        "White Street",
        "Canterbury Court",
        "Hanover Court",
        "Amherst Street",
        "Andover Court",
        "Olive Street",
        "Cobblestone Court",
        "Church Road",
        "Route 2",
        "Monroe Street",
        "Route 10",
        "Summit Street",
        "West Avenue",
        "Court Street",
    };
}
